name: CI/CD-Pipeline

on:
  pull_request:
    branches: 
      - feature/ci-cd-setup
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - edge

jobs:
  build-and-test:
    name: Build and Tests
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: .

    - name: Build
      run: dotnet build --no-restore
      working-directory: .

    - name: Run API Tests
      run: dotnet test WebDriver.API/WebDriver.API.csproj --filter Category=API --no-build
      working-directory: WebDriver.API

    - name: Run UI Tests
      if: always()
      run: dotnet test WebDriverTests --filter Category=UI --no-build
      env:
        BROWSER: ${{ github.event.inputs.browser || 'chrome' }}
      working-directory: .

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/TestResults
          **/Screenshots
          **/*.trx
